apiVersion: apps/v1
kind: Deployment
metadata:
  name: motd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motd
  template:
    metadata:
      labels:
        app: motd
    spec:
      containers:
      - name: motd
        image: jeanmassip/tp903:1.04
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        volumeMounts:
          - mountPath: /cache
            name: cache-volume
        env:
        - name: APPPORT
          valueFrom:
            configMapKeyRef:
              name: motd-configmap
              key: appport
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: motd-configmap
              key: message
        - name: DB_URI
          valueFrom:
            configMapKeyRef:
              name: motd-configmap
              key: dburi
      initContainers:
        - name: motd-init
          image: jeanmassip/tp903_init:1.03
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: motd-configmap
                  key: message
            - name: DB_URI
              valueFrom:
                configMapKeyRef:
                  name: motd-configmap
                  key: dburi
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: 100Ki
